sudo: false
services:
  - mongodb
env:
  global:
    - NODE_ENV=test
    - JWT_SECRET=authors_haven@secret
    - DATABASE_URL_TEST=mongodb://localhost:27017/tech_community_test
language: node_js
node_js:
  - '10.15.1'
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
install:
  - npm install
script:
  - npm run test:seed
after_success:
  - npm run coveralls
